trigger:
- main

pool:
  name: Default  # Replace with your self-hosted agent pool

stages:
- stage: Build
  jobs:
  - job: BuildReactApp
    steps:
    - task: UseNode@1
      inputs:
        version: '20.x'  # Ensure Node.js v20 is used

    - script: |
        echo "Installing dependencies..."
        npm ci
      displayName: 'Install Dependencies'

    - script: |
        echo "Building React app..."
        npm run build
      displayName: 'Build React App'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'build'
        artifactName: 'ReactBuild'
      displayName: 'Publish Build Artifacts'
