trigger:
- main

pool:
  name: Default # Replace with the name of your self-hosted agent pool

variables:
  imageName: 'react-app'
  imageTag: 'v1.0'

stages:
- stage: Build
  jobs:
  - job: BuildImage
    steps:
    - task: UseNode@1
      inputs:
        version: '20.x' # Ensure Node.js v20 is used

    - script: |
        echo "Checking for missing files..."
        ls -l src/pages || ls -l src/Pages
      displayName: 'Debug: Check if files exist'

    - script: |
        echo "Cleaning up old dependencies..."
        rm -rf node_modules package-lock.json
        npm install
      displayName: 'Install Dependencies'

    - script: |
        echo "Building React app..."
        npm run build
      displayName: 'Build React App'

    - script: |
        echo "Building Docker image..."
        docker build -t $(imageName):$(imageTag) .
      displayName: 'Build Docker Image'
