trigger:
- main

pool:
  name: Default  # Replace with the name of your self-hosted agent pool

variables:
  imageName: 'react-app'
  imageTag: 'v1.0'

stages:
- stage: Build
  jobs:
  - job: BuildImage
    steps:
    - task: UseNode@1
      inputs:
        version: '20.x'  # Ensure Node.js v20 is used

    - script: |
        echo "Checking file structure before build..."
        dir /s src\pages
      displayName: 'Debug File Structure'

    - script: |
        echo "Fixing case sensitivity issues..."
        rename-item src/pages/Contactform.css src/pages/Contactform_temp.css
        rename-item src/pages/Contactform_temp.css src/pages/Contactform.css
      displayName: 'Fix Case-Sensitivity Issues'
      continueOnError: true  # Allow pipeline to continue if this fails

    - script: |
        echo "Installing dependencies..."
        npm ci
      displayName: 'Install Dependencies'

    - script: |
        echo "Building React app..."
        npm run build
      displayName: 'Build React App'

    - script: |
        echo "Building Docker image..."
        docker build --no-cache -t $(imageName):$(imageTag) .
      displayName: 'Build Docker Image'
